### ISSUE TITLE
Potential TFTP Bugs in Development Branch

### ISSUE THREAD

**Issue by pbertera** [psychomario/PyPXE#66] opened 2015-04-16 21:27 UTC
I found some issues in TFTP in development branch:

1) Error message isn't closed with a null char (see L72 pbertera/PyPXE@6a95bf8e31b06ec461f2b871598efe5c4d1c3ca4)
2) sock in "ongoing" are not initialised for data transfers (see L132 pbertera/PyPXE@6a95bf8e31b06ec461f2b871598efe5c4d1c3ca4)
3) blocks are never sent (see L133 pbertera/PyPXE@6a95bf8e31b06ec461f2b871598efe5c4d1c3ca4)

I did this patch only looking at differences between master brench where TFTP is working, so can contains issues. I did some tests and seems working as well.

**Comment by psychomario** [comment] 2015-04-16 21:33
1) is valid, RFC says it should be null terminated.

I can't reproduce 2 and 3, files are being sent properly and are all recieved correctly.

**Comment by pbertera** [comment] 2015-04-16 21:41
About 2 and 3: I have a vanilla "development" branch here, I send TFTP requests using a tftp client (linux netkit) I receive nothing. Looking the code at `tftp.py` I can't understand how should work: if opcode is 1 `sendBlock()`is never called..

**Comment by psychomario** [comment] 2015-04-16 21:50
`sendBlock` isn't used for an opcode of 1. For an opcode of 1 we so some options handshake on [L127](https://github.com/psychomario/PyPXE/blob/development/pypxe/tftp.py#L127), and then we `sendBlock` after the ack.

I've managed to reproduce the error (busybox works, tftp-hpa doesn't). It seems to be related to the lack of `tsize` being sent

**Comment by psychomario** [comment] 2015-04-16 22:00
Your fix isn't quite right. We only want to use sendBlock if not response, and you might as well move `self.ongoing[address]['sock'] = socknew` up to just after the `bind()`.

The bug is becuase some clients don't use the tftp extensions such as `tsize` or `blksize`.

Note that although this should be fixed, both the Intel and iPXE PXE clients use the extensions, this is not an acceptable standalone tftp server.

**Comment by psychomario** [comment] 2015-04-17 17:42
This has been fixed now.

**Closed by psychomario** 2015-04-17 17:42 UTC
Labels: bug
